### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by lindseymanzano** [kevku/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [ ] All screenshots correspond to the described steps
  - make sure to include an example and screenshot for the last step!
- [ ] All titles of sections are formatted as headers or similar
  - make sure each section on the lab report directions doc has it's own individual header.
- [ ] Lab report is on its own page, not the index page
  - make sure each lab report is in it's own lab-report-number.md file and not in index.md. For clarification, index.md will act as the home page of this repo. You can create a table of contents in index.md that includes links to each lab report file to optimize organization.
- [ ] Last example shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Looks great! Just fix those things and submit a regrade request for full points:)

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by kevku** [comment]
I've explicitly gave new headers corresponding to the lab report directions and I moved the lab report to another .md file. Also I added screenshots to show how to optimize remote running.
